### ISSUE TITLE
After adding, can't run app on iOS Simulator M1

### ISSUE THREAD

**Issue by armandojimenez** [Skyost/FlutterFundingChoices#10]
Hi, after adding this package, I can't run my app on my iOS simulator on an M1 Mac, getting this error:

```
 /Users/armandojimenez/Development/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_funding_choices-0.2.0/ios/Classes/SwiftFlutterFundingChoicesPlugin.swift:3:8: error: no such module 'UserMessagingPlatform'
    import UserMessagingPlatform
           ^
78
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

```

**Comment by Skyost** [comment]
I'm not an expert of pods and all of this, but go to the _ios_ folder and run `pod install` and it may work after that.

**Comment by Andre-lbc** [comment]
Hi! First: thanks for the plugin!

I am also having that same error (but on an Intel Mac). In my case, it started happening after I upgraded the Flutter SDK (to 2.2.0) along with some dependencies, one of them being Firebase, which started to require an iOS deployment target of 10 or higher (as seen here: https://firebase.flutter.dev/docs/installation/ios#ios-supported-versions). I've tried to remove and reinstall all pods, to no avail. I even created a new project with just the same pubspec and had the same results.

I think the main problem here is that the reference to Google UMP SDK we are using needs to be updated (latest version as of writing is 2.0.0, and I believe this plugin is currently using 1.0.0 for android and 1.3.0 for iOS). I also think we should bump the iOS "platform" version on the podspec to 10.0, here: https://github.com/Skyost/FlutterFundingChoices/blob/8ef4cb21fa2d5a3c503638f7ca14e57abb0dc06d/ios/flutter_funding_choices.podspec#L18
Admob currently requires 10.0 or later (https://developers.google.com/admob/ios/quick-start), so now that we have ads and analytics on 10.0, I think we can stop using 9.0.

UMP SDK versions and release notes:
https://developers.google.com/admob/ump/ios/download

BTW 1: Version 1.4.0 states: "Included an arm64 slice for simulators to support testing on Apple Silicon devices.", I think this is the fix for his problem.

BTW 2: I could try to fork and try a PR, but I have just a sliver of an idea on how these plugins work, so it would probably take more time than actually needed.

**Comment by Andre-lbc** [comment]
Hello again. So, I ended up forking it and updated accordingly, which apparently resolved my problem. I am now using it in two of my apps, so far without issues. Would you like me to make a pull request?

My fork:
https://github.com/Andre-lbc/FlutterFundingChoices

**Comment by Skyost** [comment]
@Andre-lbc Great ! It would be very nice of you if you could submit a pull request :wink:

**Comment by Andre-lbc** [comment]
Sorry for the delay. I've just submitted it: #13  😬

**Comment by Skyost** [comment]
Forgot to link it with #13, but I think we can close it now.
