### ISSUE TITLE
Ability to use the setDebugGeography() method

### ISSUE THREAD

**Issue by Kobatsu** [Skyost/FlutterFundingChoices#11]
Can we have access to the setDebugGeography() method to test how our app react?

I saw that it's available on the Android part: https://developers.google.com/admob/ump/android/quick-start

It can be used for non-EU devs to test their app in EU but it is also useful for EU devs to test their app in non-EU countries (like me!).

Due to some bad handling, users of my app outside of EU are not seeing any ads and my analytics don't work because I messed up with the funding choices. They are enabled only if you accept the Funding Choices dialog, but it is not shown outside EU I think.
I would like to verify this and correct it but I can't really test it since I'm in EU! 😅

**Comment by Kobatsu** [comment]
I am working on a PR with the changes I have in mind

**Comment by nzackoya** [comment]
When will this be available?

**Comment by Skyost** [comment]
@nzackoya I'm waiting for the PR... You're free to submit it if you want 😄

**Comment by nzackoya** [comment]
@Skyost You were waiting for me for 6 months?  Well, I'm not sure if this plugin even works, cause I still can't make this consent dialog show up, even with reseting every time, with England vpn, with France region setting and with tagForUnderAgeOfConsent: true and testDevicesHashedIds. But I believe you have already this flag activated if testDeviceHashedIds were added according to your comment in the code
/// [testDevicesHashedIds] Provide test devices id in order to force geography to the EEA. But it doesn't do anything and it doesn't work. So I hoped if this feature setDebugGeography() could anyhow make this plugin work.

**Comment by nzackoya** [comment]
If you are not going to support the plugin, then it makes no sense to use it, and you should flag it as deprecated/not supported

**Comment by Kobatsu** [comment]
I already made a PR a while ago, you said you didn't have time to review it.
I forked it and I am using this fork due to this...

**Comment by Skyost** [comment]
My bad.

**Comment by nzackoya** [comment]
@Kobatsu in your repo there is a bug in here I guess debugGeography: (arguments["debugGeography"] as? [Int]) ?? UMPDebugGeography.disabled, result: result)

**Comment by nzackoya** [comment]
@Skyost can you please fix it ^  in your version

**Comment by Kobatsu** [comment]
I am not familiar with iOS and Swift. Maybe @Skyost has a better idea on the correct syntax if it's not working.
